server:
  port: 33590

spring:
  application:
    name: dztz-b00t3
  datasource:
#    url: jdbc:mysql://192.168.1.88:3306/javatechie?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://local:3306/javatechie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read
              - write
        provider:
          my-provider:
            authorization-uri: https://your-authorization-server.com/oauth/authorize
            token-uri: https://your-authorization-server.com/oauth/token
            user-info-uri: https://your-authorization-server.com/userinfo
            user-name-attribute: id
mybatis:
  typeAliasesPackage: com.dztzb003.j2t.common.entity
  mapper-locations: classpath:/mapper/*.xml