server:
  port: 33590

spring:
  application:
    name: dztz-b00t3
  datasource:
#    url: jdbc:mysql://192.168.1.88:3306/javatechie?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://local:3306/javatechie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
